# Stage 1: Construir el frontend
FROM node:16 AS build-frontend
WORKDIR /app
COPY CentroServicioFrontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY CentroServicioFrontend/ .
RUN npm run build

# Stage 2: Construir la imagen de Nginx final
FROM nginx:1.24.0
COPY --from=build-frontend /app/build /usr/share/nginx/html
COPY ./nginx/default.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]